# Generated by Django 3.2.3 on 2021-07-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Categorie',
        ),
    ]
